const $=id=>document.getElementById(id);
let data=[],showZh=true,currentFile=null,pdfDoc=null,pdfBytes=null,renderScale=1,baseWidth=600,observer=null,renderTasks=new Map(),pageElements=[],pageMeta=[],pageBlocks=[],activeParagraph=-1,loadingToken=0;
let bilingualLayout=localStorage.getItem('paperreader-layout')==='side'?'side':'stack';
const storageKey='paperreader-v2-notes';
try{const old=JSON.parse(localStorage.getItem(storageKey)||'null');if(old?.data)data=old.data}catch(e){}
const save=()=>{try{localStorage.setItem(storageKey,JSON.stringify({data}))}catch(e){}};
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function updateLayout(){const el=$('paragraphs');el.classList.toggle('layout-side',bilingualLayout==='side');el.classList.toggle('layout-stack',bilingualLayout!=='side');el.classList.toggle('zh-off',!showZh);$('layoutToggle').textContent=bilingualLayout==='side'?'↕ 切换上下对照':'⇄ 切换左右对照'}
$('layoutToggle').onclick=()=>{bilingualLayout=bilingualLayout==='side'?'stack':'side';localStorage.setItem('paperreader-layout',bilingualLayout);render()};
$('translateToggle').onclick=()=>{showZh=!showZh;$('translateToggle').textContent=showZh?'👁 隐藏中文':'👁 显示中文';render()};
function render(){updateLayout();const box=$('paragraphs');box.innerHTML=data.length?'':'<p class="muted">尚无文本。导入 PDF 后点击“提取论文文本”，或者先载入示例。</p>';
 const counts={title:0,body:0,caption:0,reference:0,other:0};data.forEach(p=>counts[p.type||'body']=(counts[p.type||'body']||0)+1);
 $('paragraphStats').textContent=`共 ${data.length} 段｜标题 ${counts.title}｜正文 ${counts.body}｜图表说明 ${counts.caption}｜参考文献 ${counts.reference}${counts.other?'｜其他 '+counts.other:''}`;
 data.forEach((p,i)=>{const div=document.createElement('article');div.className='para '+(p.mark?'mark-'+p.mark:'')+(activeParagraph===i?' selected':'');div.dataset.paragraph=i;div.innerHTML=`<b>${{title:'标题',body:'正文',caption:'图表说明',reference:'参考文献',other:'其他'}[p.type||'body']} · ${i+1}${p.page?' · 第'+p.page+'页':''}</b><p lang="en">${esc(p.en)}</p><div class="zh ${showZh?'':'hidden'}"><b>中文译文</b><p>${esc(p.zh||'（尚未翻译；点击编辑译文填写）')}</p></div><div class="colors"><button data-mark="yellow">🟨</button><button data-mark="green">🟩</button><button data-mark="blue">🟦</button><button data-mark="red">🟥</button><button data-mark="">清除</button><button data-edit="1">编辑译文</button></div>`;
 div.onclick=e=>{if(e.target.closest('button'))return;selectParagraph(i,true)};
 div.querySelectorAll('[data-mark]').forEach(b=>b.onclick=()=>{p.mark=b.dataset.mark;save();render()});div.querySelector('[data-edit]').onclick=()=>{const t=prompt('输入/粘贴该段中文译文：',p.zh||'');if(t!==null){p.zh=t;save();render()}};box.appendChild(div)})}
function selectParagraph(i,scroll){activeParagraph=i;document.querySelectorAll('.para').forEach(e=>e.classList.toggle('selected',+e.dataset.paragraph===i));updateOverlays();const p=data[i];if(scroll&&p?.page&&pageElements[p.page-1]){const page=pageElements[p.page-1],vp=$('pdfViewport');const scale=page.clientWidth/(pageMeta[p.page-1]?.width||page.clientWidth);vp.scrollTo({top:page.offsetTop-vp.offsetTop+(p.box?.y||0)*scale-25,behavior:'smooth'});queueRender(p.page-1)} }
$('sampleBtn').onclick=()=>{data=[{en:'This study investigates the electrochemical performance of lithium-ion batteries.',zh:'本研究考察锂离子电池的电化学性能。',type:'body',mark:'yellow'},{en:'The electrodes were characterized using X-ray diffraction and scanning electron microscopy.',zh:'采用 X 射线衍射和扫描电子显微镜对电极进行表征。',type:'body',mark:'green'},{en:'The sample retained 92% of its initial capacity after 200 cycles.',zh:'经过 200 次循环后，样品保持了初始容量的 92%。',type:'body',mark:'blue'}];save();render()};
$('addBtn').onclick=()=>{const en=prompt('输入英文原文：');if(en?.trim()){data.push({en:en.trim(),zh:'',mark:'',type:'body'});save();render()}};
$('copyBtn').onclick=async()=>{try{await navigator.clipboard.writeText(data.map(p=>p.en).join('\n\n'));alert('已复制英文原文')}catch(e){alert('复制失败，请检查浏览器权限')}};
$('clearBtn').onclick=()=>{if(!confirm('清除当前 PDF 和段落吗？'))return;loadingToken++;if(pdfDoc)pdfDoc.destroy();pdfDoc=null;currentFile=null;pdfBytes=null;pageElements=[];pageMeta=[];pageBlocks=[];renderTasks.clear();if(observer)observer.disconnect();$('pdfPages').innerHTML='';$('file').value='';$('fileName').textContent='尚未选择 PDF';$('pageIndicator').textContent='0 / 0';data=[];save();render()};
async function loadPdfjs(){if(window.pdfjsLib)return pdfjsLib;const src='https://cdnjs.cloudflare.com/ajax/libs/pdf.js/3.11.174/pdf.min.js';await new Promise((resolve,reject)=>{const s=document.createElement('script');s.src=src;s.onload=resolve;s.onerror=reject;document.head.appendChild(s)});pdfjsLib.GlobalWorkerOptions.workerSrc='https://cdnjs.cloudflare.com/ajax/libs/pdf.js/3.11.174/pdf.worker.min.js';return pdfjsLib}
const status=$('extractStatus');
$('file').onchange=async e=>{const f=e.target.files[0];if(!f)return;if(f.type!=='application/pdf'&&!f.name.toLowerCase().endsWith('.pdf')){alert('请选择 PDF 文件');return}currentFile=f;$('fileName').textContent=f.name;await openPdf(f)};
async function openPdf(f){const token=++loadingToken;status.textContent='正在打开 PDF…';try{if(observer)observer.disconnect();if(pdfDoc)await pdfDoc.destroy();const lib=await loadPdfjs();pdfBytes=new Uint8Array(await f.arrayBuffer());const doc=await lib.getDocument({data:pdfBytes.slice()}).promise;if(token!==loadingToken){doc.destroy();return}pdfDoc=doc;renderScale=1;pageMeta=[];pageElements=[];pageBlocks=[];renderTasks.clear();$('pdfPages').innerHTML='';const first=await doc.getPage(1);baseWidth=first.getViewport({scale:1}).width;for(let i=1;i<=doc.numPages;i++){const pg=await doc.getPage(i),v=pg.getViewport({scale:1});pageMeta.push({width:v.width,height:v.height});const el=document.createElement('div');el.className='pdf-page';el.dataset.page=i;el.innerHTML='<div class="page-placeholder">第 '+i+' 页</div><div class="paragraph-overlay"></div>';pageElements.push(el);$('pdfPages').appendChild(el)}layoutPages();setupObserver();$('pageIndicator').textContent=`1 / ${doc.numPages}`;status.textContent=`PDF 已打开：${doc.numPages} 页。点击“提取论文文本”识别段落。`;}catch(err){status.textContent='打开 PDF 失败：'+err.message+'。请检查网络或 PDF 文件。'}}
function layoutPages(){if(!pdfDoc)return;const w=Math.max(120,$('pdfViewport').clientWidth-16)*renderScale;pageElements.forEach((el,i)=>{const m=pageMeta[i];el.style.width=w+'px';el.style.height=(w*m.height/m.width)+'px';el.style.maxWidth='none'});$('zoomLabel').textContent=Math.round(renderScale*100)+'%';for(const el of pageElements){const c=el.querySelector('canvas');if(c)c.remove();el.querySelector('.pdf-text-layer')?.remove();if(!el.querySelector('.page-placeholder')){const ph=document.createElement('div');ph.className='page-placeholder';ph.textContent='第 '+el.dataset.page+' 页';el.prepend(ph)}}renderTasks.clear();updateOverlays();if(observer)setupObserver()}
function setupObserver(){if(observer)observer.disconnect();const vp=$('pdfViewport');observer=new IntersectionObserver(entries=>{for(const e of entries)if(e.isIntersecting)queueRender(+e.target.dataset.page-1);evictFarPages()},{root:vp,rootMargin:'900px 0px'});pageElements.forEach(e=>observer.observe(e))}
function evictFarPages(){const vp=$('pdfViewport'),mid=vp.scrollTop+vp.clientHeight/2;pageElements.forEach((el,i)=>{if(Math.abs(el.offsetTop+el.offsetHeight/2-mid)>vp.clientHeight*3.5){el.querySelector('canvas')?.remove();el.querySelector('.pdf-text-layer')?.remove();if(!el.querySelector('.page-placeholder')){const ph=document.createElement('div');ph.className='page-placeholder';ph.textContent='第 '+(i+1)+' 页';el.prepend(ph)}}})}
async function queueRender(i){if(!pdfDoc||i<0||i>=pageElements.length)return;const el=pageElements[i];if(el.querySelector('canvas')||renderTasks.has(i))return;const token=loadingToken;const task=(async()=>{try{const page=await pdfDoc.getPage(i+1);if(token!==loadingToken)return;const width=el.clientWidth,view=page.getViewport({scale:width/pageMeta[i].width}),dpr=Math.min(window.devicePixelRatio||1,2);const canvas=document.createElement('canvas');canvas.width=Math.ceil(view.width*dpr);canvas.height=Math.ceil(view.height*dpr);canvas.style.width='100%';canvas.style.height='100%';const ctx=canvas.getContext('2d',{alpha:false});await page.render({canvasContext:ctx,viewport:view,transform:[dpr,0,0,dpr,0,0]}).promise;if(token!==loadingToken)return;el.querySelector('.page-placeholder')?.remove();el.prepend(canvas);const tc=await page.getTextContent();if(token!==loadingToken)return;const layer=document.createElement('div');layer.className='pdf-text-layer';const style=getComputedStyle(el);const factor=el.clientWidth/pageMeta[i].width;for(const item of tc.items){if(!item.str?.trim())continue;const t=item.transform,span=document.createElement('span');span.textContent=item.str;const x=t[4]*factor,y=(pageMeta[i].height-t[5])*factor;const font=Math.max(1,Math.hypot(t[2],t[3])*factor);span.style.cssText=`left:${x}px;top:${y-font}px;font-size:${font}px;font-family:sans-serif;`;layer.appendChild(span);const approx=span.getBoundingClientRect().width;if(approx>0&&item.width)span.style.transform=`scaleX(${item.width*factor/approx})`;}el.appendChild(layer);updateOverlays()}catch(err){console.warn('PDF page render failed',i+1,err)}finally{renderTasks.delete(i)}})();renderTasks.set(i,task);await task}
$('zoomIn').onclick=()=>{renderScale=Math.min(3,+(renderScale*1.25).toFixed(2));layoutPages()};$('zoomOut').onclick=()=>{renderScale=Math.max(.6,+(renderScale/1.25).toFixed(2));layoutPages()};
$('goPage').onclick=()=>{const n=Math.floor(+$('pageJump').value);if(!pdfDoc||n<1||n>pdfDoc.numPages)return alert('请输入有效页码');$('pdfViewport').scrollTo({top:pageElements[n-1].offsetTop-pageElements[0].offsetTop,behavior:'smooth'});queueRender(n-1)};
$('pageJump').onkeydown=e=>{if(e.key==='Enter')$('goPage').click()};
$('pdfViewport').onscroll=()=>{if(!pdfDoc)return;const vp=$('pdfViewport');let best=0,dist=Infinity;pageElements.forEach((el,i)=>{const d=Math.abs(el.offsetTop-pageElements[0].offsetTop-vp.scrollTop);if(d<dist){dist=d;best=i}});$('pageIndicator').textContent=`${best+1} / ${pdfDoc.numPages}`};
$('debugBoxes').onchange=updateOverlays;
function updateOverlays(){pageElements.forEach((el,i)=>{const layer=el.querySelector('.paragraph-overlay');if(!layer)return;layer.innerHTML='';layer.classList.toggle('debug',$('debugBoxes').checked);const factor=el.clientWidth/(pageMeta[i]?.width||1);data.forEach((p,j)=>{if(p.page!==i+1||!p.box)return;const b=document.createElement('div');b.className='box'+(j===activeParagraph?' active':'');b.style.cssText=`left:${p.box.x*factor}px;top:${p.box.y*factor}px;width:${p.box.w*factor}px;height:${p.box.h*factor}px`;layer.appendChild(b)})})}
// Layout-aware PDF extraction: glyph coordinates -> lines -> columns -> paragraphs.
function extractLines(items,meta){const glyphs=items.filter(t=>t.str?.trim()&&t.transform).map(t=>({str:t.str,x:t.transform[4],y:meta.height-t.transform[5],w:t.width||0,h:Math.max(1,Math.hypot(t.transform[2],t.transform[3])),font:t.fontName||''})).filter(t=>t.y>=0&&t.y<=meta.height+5);glyphs.sort((a,b)=>a.y-b.y||a.x-b.x);const lines=[];for(const g of glyphs){let line=lines.findLast?.(l=>Math.abs(l.y-g.y)<Math.max(2,Math.min(l.h,g.h)*.35));if(!line){line={y:g.y,h:g.h,items:[]};lines.push(line)}line.items.push(g);line.h=Math.max(line.h,g.h)}return lines.map(l=>{l.items.sort((a,b)=>a.x-b.x);l.x=Math.min(...l.items.map(a=>a.x));l.right=Math.max(...l.items.map(a=>a.x+a.w));l.text='';let prev=null;for(const t of l.items){if(prev){const gap=t.x-(prev.x+prev.w);if(gap>Math.max(1.5,l.h*.19)&&!l.text.endsWith(' ')&&!t.str.startsWith(' '))l.text+=' '}l.text+=t.str;prev=t}l.text=l.text.replace(/\s+/g,' ').trim();return l}).filter(l=>l.text.length>1)}
function columnOrder(lines,meta){const W=meta.width;const interior=lines.filter(l=>l.y>meta.height*.11&&l.y<meta.height*.87&&l.right-l.x<W*.72);const left=interior.filter(l=>l.x<W*.46&&l.right<W*.61).length,right=interior.filter(l=>l.x>W*.46).length;const two=left>5&&right>5;const mid=W*.50;const label=l=>!two||l.right-l.x>W*.72?'full':l.x<mid?'left':'right';const sorted=lines.slice();if(two){sorted.sort((a,b)=>{const ca=label(a),cb=label(b);const ra=ca==='left'?0:ca==='right'?1:-1,rb=cb==='left'?0:cb==='right'?1:-1;if(ra!==rb){if(ra===-1||rb===-1)return a.y-b.y;return ra-rb}return a.y-b.y||a.x-b.x})}else sorted.sort((a,b)=>a.y-b.y||a.x-b.x);return{lines:sorted,two,label}}
function mergeText(a,b){return /[A-Za-z]-$/.test(a)?a.slice(0,-1)+b:a+' '+b}
function buildPageParagraphs(raw,pageNo,meta){const ordered=columnOrder(extractLines(raw.items,meta),meta),lines=ordered.lines;if(!lines.length)return[];const median=a=>{const x=a.slice().sort((a,b)=>a-b);return x[Math.floor(x.length/2)]||0};const bodySize=median(lines.filter(l=>l.y>meta.height*.12&&l.y<meta.height*.88).map(l=>l.h));const out=[];let group=[],refMode=false;
 const flush=()=>{if(!group.length)return;const text=group.reduce((a,l)=>a?mergeText(a,l.text):l.text,'').trim();const x=Math.min(...group.map(l=>l.x)),right=Math.max(...group.map(l=>l.right)),top=Math.min(...group.map(l=>l.y-l.h)),bottom=Math.max(...group.map(l=>l.y+l.h*.3));const font=median(group.map(l=>l.h));let type='body';if(/^(figure|fig\.?|table|scheme|图\s*\d)/i.test(text))type='caption';else if(/^(references|bibliography|参考文献)$/i.test(text)){type='title';refMode=true}else if(refMode||/^\[\d+\]\s/.test(text)||/^\d+\.\s+[A-Z][a-z]+,/.test(text))type='reference';else if(font>bodySize*1.22||group.length<=2&&text.length<95&&/^(abstract|introduction|conclusions?|results|discussion|methods|experimental|\d+(\.\d+)*\s+[A-Z])/i.test(text))type='title';out.push({en:text,zh:'',mark:'',type,page:pageNo,box:{x,y:top,w:right-x,h:bottom-top}});group=[]};
 let prev=null;for(const l of lines){const t=l.text;if((l.y<meta.height*.07||l.y>meta.height*.94)&&(/\bdoi\b|©|copyright|journal|volume|www\.|^\d{1,3}$|^page\s*\d+/i.test(t)||t.length<55))continue;if(/^(received|accepted|published|corresponding author|affiliation|department of|school of|institute of|university of|email\s*:)/i.test(t))continue;
 const col=ordered.label(l),prevCol=prev?ordered.label(prev):col;const gap=prev?l.y-prev.y:0;const sameCol=prev&&col===prevCol;const usual=prev?Math.max(prev.h,l.h):l.h;const indentation=prev&&l.x-prev.x>usual*1.6;const titleFont=l.h>bodySize*1.25;const prevTitle=prev&&prev.h>bodySize*1.25;const newBlock=!prev||!sameCol||gap>usual*1.85||gap<-.2||indentation||titleFont!==prevTitle||/^(figure|fig\.?|table|scheme|references|bibliography)/i.test(t);
 if(newBlock)flush();group.push(l);prev=l}flush();return out.filter(p=>p.en.length>3)}
$('extractBtn').onclick=async()=>{if(!pdfDoc){alert('请先导入 PDF');return}const token=loadingToken;status.textContent='正在按坐标分析论文段落…';try{const paragraphs=[];for(let i=1;i<=pdfDoc.numPages;i++){if(token!==loadingToken)return;status.textContent=`正在分析第 ${i} / ${pdfDoc.numPages} 页…`;const page=await pdfDoc.getPage(i);const content=await page.getTextContent();paragraphs.push(...buildPageParagraphs(content,i,pageMeta[i-1]));await new Promise(r=>setTimeout(r,0))}if(token!==loadingToken)return;data=paragraphs;activeParagraph=-1;save();render();updateOverlays();status.textContent=`提取完成：${pdfDoc.numPages} 页，共 ${data.length} 段。分类统计见右侧。可勾选“显示段落框”核对识别效果。`;}catch(err){status.textContent='提取失败：'+err.message}};
function sentences(){return data.map(x=>x.en).filter(Boolean)}
function summary(){const ss=sentences();if(!ss.length)return"请先导入并提取论文文本，或载入示例。";return"文献文本概览（规则提取，非 AI 总结）：\n"+"段落数："+ss.length+"\n\n代表性段落：\n"+ss.slice(0,6).map((x,i)=>`${i+1}. ${x.slice(0,220)}`).join("\n")}
$("outlineBtn").onclick=()=>{$("outline").textContent=summary()};
$("mindBtn").onclick=()=>{const target=$("mind");target.innerHTML="";if(!data.length){target.textContent="请先导入并提取文本。";return}const root=document.createElement("b");root.textContent="📘 论文内容";target.appendChild(root);data.slice(0,10).forEach((p,i)=>{const d=document.createElement("div");d.className="mind-item";d.textContent=`├─ ${i+1}. ${p.en.slice(0,100)}${p.en.length>100?"…":""}`;target.appendChild(d)})};
$("askBtn").onclick=()=>{const q=$("question").value.trim();if(!q){alert("请输入问题");return}$("answer").textContent="当前未连接 AI 后端，无法生成可靠的智能回答。\n\n你问的是："+q+"\n\n"+summary()+"\n\n提示：这是本地规则摘要，不是 AI 分析。"};
$("exportBtn").onclick=()=>{const blob=new Blob([JSON.stringify({exportedAt:new Date().toISOString(),data},null,2)],{type:"application/json"});const url=URL.createObjectURL(blob);const a=document.createElement("a");a.href=url;a.download="PaperReaderAI_notes.json";a.click();setTimeout(()=>URL.revokeObjectURL(url),2000)};
$("resetBtn").onclick=()=>{if(confirm("确定删除当前浏览器保存的全部译文与标记？")){data=[];save();render()}};
render();
