const $=id=>document.getElementById(id);
let data=[],showZh=true,pdfUrl=null,currentFile=null;
let bilingualLayout=localStorage.getItem("paperreader-layout")==="side"?"side":"stack";
function updateLayout(){const el=$("paragraphs");el.classList.toggle("layout-side",bilingualLayout==="side");el.classList.toggle("layout-stack",bilingualLayout!=="side");el.classList.toggle("zh-off",!showZh);$("layoutToggle").textContent=bilingualLayout==="side"?"↕ 切换上下对照":"⇄ 切换左右对照";}
$("layoutToggle").onclick=()=>{bilingualLayout=bilingualLayout==="side"?"stack":"side";localStorage.setItem("paperreader-layout",bilingualLayout);updateLayout()};
const storageKey="paperreader-v2-notes";
try{const old=JSON.parse(localStorage.getItem(storageKey)||"null");if(old?.data)data=old.data;}catch(e){}
const save=()=>{try{localStorage.setItem(storageKey,JSON.stringify({data}));}catch(e){}};
const esc=s=>String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
function render(){updateLayout();const box=$("paragraphs");box.innerHTML=data.length?"":'<p class="muted">尚无文本。导入 PDF 后点击“提取论文文本”，或者先载入示例。</p>';data.forEach((p,i)=>{let div=document.createElement("article");div.className="para "+(p.mark?"mark-"+p.mark:"");div.innerHTML=`<b>段落 ${i+1}</b><p lang="en">${esc(p.en)}</p><div class="zh ${showZh?"":"hidden"}"><b>中文译文</b><p>${esc(p.zh||"（尚未翻译；点击编辑译文填写）")}</p></div><div class="colors"><button data-mark="yellow">🟨</button><button data-mark="green">🟩</button><button data-mark="blue">🟦</button><button data-mark="red">🟥</button><button data-mark="">清除</button><button data-edit="1">编辑译文</button></div>`;div.querySelectorAll("[data-mark]").forEach(b=>b.onclick=()=>{p.mark=b.dataset.mark;save();render()});div.querySelector("[data-edit]").onclick=()=>{let t=prompt("输入/粘贴该段中文译文：",p.zh||"");if(t!==null){p.zh=t;save();render()}};box.appendChild(div)})}
$("translateToggle").onclick=()=>{showZh=!showZh;$("translateToggle").textContent=showZh?"👁 隐藏中文":"👁 显示中文";render()};
$("file").onchange=e=>{const f=e.target.files[0];if(!f)return;if(f.type!=="application/pdf"&&!f.name.toLowerCase().endsWith(".pdf")){alert("请选择 PDF 文件");return}currentFile=f;if(pdfUrl)URL.revokeObjectURL(pdfUrl);pdfUrl=URL.createObjectURL(f);$("pdf").src=pdfUrl;$("fileName").textContent=f.name;$("extractStatus").textContent="PDF 已导入。点击“提取论文文本”读取文本层。";};
$("sampleBtn").onclick=()=>{data=[{en:"This study investigates the electrochemical performance of lithium-ion batteries.",zh:"本研究考察锂离子电池的电化学性能。",mark:"yellow"},{en:"The electrodes were characterized using X-ray diffraction and scanning electron microscopy.",zh:"采用 X 射线衍射和扫描电子显微镜对电极进行表征。",mark:"green"},{en:"The sample retained 92% of its initial capacity after 200 cycles.",zh:"经过 200 次循环后，样品保持了初始容量的 92%。",mark:"blue"}];save();render()};
$("addBtn").onclick=()=>{const en=prompt("输入英文原文：");if(en?.trim()){data.push({en:en.trim(),zh:"",mark:""});save();render()}};
$("copyBtn").onclick=async()=>{try{await navigator.clipboard.writeText(data.map(p=>p.en).join("\n\n"));alert("已复制英文原文")}catch(e){alert("复制失败，请检查浏览器权限")}};
$("clearBtn").onclick=()=>{if(!confirm("清除当前 PDF 和段落吗？"))return;if(pdfUrl)URL.revokeObjectURL(pdfUrl);pdfUrl=null;currentFile=null;$("pdf").removeAttribute("src");$("file").value="";$("fileName").textContent="尚未选择 PDF";data=[];save();render()};
async function loadPdfjs(){if(window.pdfjsLib)return window.pdfjsLib;const src="https://cdnjs.cloudflare.com/ajax/libs/pdf.js/3.11.174/pdf.min.js";await new Promise((resolve,reject)=>{const s=document.createElement("script");s.src=src;s.onload=resolve;s.onerror=reject;document.head.appendChild(s)});pdfjsLib.GlobalWorkerOptions.workerSrc="https://cdnjs.cloudflare.com/ajax/libs/pdf.js/3.11.174/pdf.worker.min.js";return pdfjsLib}
$("extractBtn").onclick=async()=>{if(!currentFile){alert("请先导入 PDF");return}const status=$("extractStatus");status.textContent="正在加载 PDF 文本解析组件……";try{const lib=await loadPdfjs();const bytes=new Uint8Array(await currentFile.arrayBuffer());const pdf=await lib.getDocument({data:bytes}).promise;const blocks=[];for(let i=1;i<=pdf.numPages;i++){status.textContent=`正在提取第 ${i}/${pdf.numPages} 页……`;const page=await pdf.getPage(i);const content=await page.getTextContent();let line="";let prevY=null;for(const item of content.items){if(!item.str)continue;const y=item.transform?.[5];if(prevY!==null&&Math.abs(y-prevY)>4){if(line.trim())blocks.push(line.trim());line=""}line+=(line&&/^[A-Za-z0-9]/.test(item.str)?" ":"")+item.str;prevY=y}if(line.trim())blocks.push(line.trim())}data=blocks.filter(t=>t.length>2).slice(0,1000).map(en=>({en,zh:"",mark:""}));save();render();status.textContent=`提取完成：${pdf.numPages} 页、${data.length} 段。扫描版 PDF（纯图片）需要 OCR，当前不支持。`;}catch(err){status.textContent="提取失败："+err.message+"。请确认联网且 PDF 含有可选中文本。"}};
function sentences(){return data.map(x=>x.en).filter(Boolean)}
function summary(){const ss=sentences();if(!ss.length)return"请先导入并提取论文文本，或载入示例。";return"文献文本概览（规则提取，非 AI 总结）：\n"+"段落数："+ss.length+"\n\n代表性段落：\n"+ss.slice(0,6).map((x,i)=>`${i+1}. ${x.slice(0,220)}`).join("\n")}
$("outlineBtn").onclick=()=>{$("outline").textContent=summary()};
$("mindBtn").onclick=()=>{const target=$("mind");target.innerHTML="";if(!data.length){target.textContent="请先导入并提取文本。";return}const root=document.createElement("b");root.textContent="📘 论文内容";target.appendChild(root);data.slice(0,10).forEach((p,i)=>{const d=document.createElement("div");d.className="mind-item";d.textContent=`├─ ${i+1}. ${p.en.slice(0,100)}${p.en.length>100?"…":""}`;target.appendChild(d)})};
$("askBtn").onclick=()=>{const q=$("question").value.trim();if(!q){alert("请输入问题");return}$("answer").textContent="当前未连接 AI 后端，无法生成可靠的智能回答。\n\n你问的是："+q+"\n\n"+summary()+"\n\n提示：这是本地规则摘要，不是 AI 分析。"};
$("exportBtn").onclick=()=>{const blob=new Blob([JSON.stringify({exportedAt:new Date().toISOString(),data},null,2)],{type:"application/json"});const url=URL.createObjectURL(blob);const a=document.createElement("a");a.href=url;a.download="PaperReaderAI_notes.json";a.click();setTimeout(()=>URL.revokeObjectURL(url),2000)};
$("resetBtn").onclick=()=>{if(confirm("确定删除当前浏览器保存的全部译文与标记？")){data=[];save();render()}};
render();
